# Generated by Django 5.1 on 2024-08-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time_start', models.TimeField()),
                ('visit_time_end', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('purpose_of_visit', models.TextField()),
                ('visitors', models.CharField(max_length=255)),
                ('field_contact_person', models.CharField(max_length=255)),
                ('field_contact_person_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_description', models.TextField()),
                ('weather_conditions', models.CharField(max_length=255)),
                ('site_accessibility', models.TextField()),
                ('general_observations', models.TextField()),
                ('plant_health_status', models.TextField()),
                ('pest_activity', models.TextField()),
                ('soil_conditions', models.TextField()),
                ('infrastructure_condition', models.TextField()),
                ('problems_identified', models.TextField()),
                ('recommendations', models.TextField()),
                ('immediate_actions', models.TextField()),
                ('follow_up_actions', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('challenges_encountered', models.TextField(blank=True, null=True)),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, to='FieldVisit.photo')),
            ],
        ),
    ]
