# Generated by Django 5.1 on 2024-08-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldVisit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvisitreport',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='fieldvisitreport',
            name='follow_up_actions',
        ),
        migrations.RemoveField(
            model_name='fieldvisitreport',
            name='site_accessibility',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
