# Generated by Django 5.1 on 2024-08-19 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('inspection_time', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('inspector_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_id', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('contact_information', models.CharField(max_length=255)),
                ('product_list', models.TextField()),
                ('license_display', models.BooleanField(default=False)),
                ('compliance_with_regulations', models.BooleanField(default=False)),
                ('restricted_products', models.BooleanField(default=False)),
                ('safety_measures', models.TextField(blank=True)),
                ('documentation', models.TextField(blank=True)),
                ('violations_detected', models.TextField(blank=True)),
                ('non_compliant_products', models.TextField(blank=True)),
                ('corrective_actions_required', models.TextField(blank=True)),
                ('follow_up_inspection_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('immediate_actions', models.TextField(blank=True)),
                ('penalties_issued', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('photographic_evidence', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('product_samples', models.FileField(blank=True, null=True, upload_to='product_samples/')),
                ('correspondence', models.FileField(blank=True, null=True, upload_to='correspondence/')),
                ('challenges_encountered', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('recommendations_for_improvement', models.TextField(blank=True)),
            ],
        ),
    ]
