# Generated by Django 5.1 on 2024-08-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PesticideInspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='compliance_with_regulations',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='correspondence',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='license_display',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='product_samples',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='restricted_products',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='safety_measures',
        ),
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='seller_id',
        ),
    ]
