# Generated by Django 5.1 on 2024-08-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PesticideInspection', '0002_remove_pesticideinspection_compliance_with_regulations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='immediate_actions',
        ),
    ]
