# Generated by Django 5.1 on 2024-08-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PesticideInspection', '0003_remove_pesticideinspection_immediate_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticideinspection',
            name='recommendations',
        ),
    ]
