# Generated by Django 5.1 on 2024-08-19 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHealthInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('inspection_time', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(choices=[('airport', 'Airport'), ('border_point', 'Border Point'), ('seaport', 'Seaport')], max_length=50)),
                ('inspector_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('condition_of_items', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('pests_diseases_detected', models.TextField(blank=True)),
                ('infestation_level', models.CharField(max_length=50)),
                ('laboratory_analysis_required', models.BooleanField(default=False)),
                ('sample_collected', models.BooleanField(default=False)),
                ('quarantine_required', models.BooleanField(default=False)),
                ('items_seized', models.BooleanField(default=False)),
                ('immediate_actions', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('challenges_encountered', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('recommendations_for_improvement', models.TextField(blank=True)),
            ],
        ),
    ]
