# Generated by Django 5.1 on 2024-08-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantInspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planthealthinspection',
            name='packaging',
        ),
    ]
