# Generated by Django 5.1 on 2024-08-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantInspection', '0002_remove_planthealthinspection_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planthealthinspection',
            name='infestation_level',
        ),
    ]
