# Generated by Django 5.1 on 2024-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantInspection', '0003_remove_planthealthinspection_infestation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planthealthinspection',
            name='location',
            field=models.CharField(choices=[('tunduma', 'Tunduma'), ('kasumulu', 'Kasumulu'), ('songwe', 'Songwe')], max_length=50),
        ),
    ]
