# Generated by Django 5.1 on 2024-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantInspection', '0004_alter_planthealthinspection_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planthealthinspection',
            name='recommendations',
        ),
    ]
