# Generated by Django 5.1 on 2024-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_time_start', models.TimeField()),
                ('meeting_time_end', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('attendees', models.TextField()),
                ('agenda_items', models.TextField()),
                ('presenter_lead', models.TextField()),
                ('key_points_discussed', models.TextField()),
                ('decisions_made', models.TextField()),
                ('action_items', models.TextField()),
                ('documents', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('next_meeting', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
