# Generated by Django 5.1 on 2024-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreport',
            name='action_items',
        ),
        migrations.RemoveField(
            model_name='meetingreport',
            name='links',
        ),
        migrations.AlterField(
            model_name='meetingreport',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
