# Generated by Django 5.1 on 2024-08-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0002_remove_meetingreport_action_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreport',
            name='documents',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Meetings.meetingreport')),
            ],
        ),
    ]
