# Generated by Django 5.1 on 2024-08-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0003_remove_meetingreport_documents_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreport',
            name='next_meeting',
        ),
    ]
