# Generated by Django 5.1 on 2024-08-20 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('station', models.CharField(choices=[('mtwara', 'Mtwara'), ('mtambaswala', 'Mtambaswala'), ('kasesya', 'Kasesya'), ('kirando', 'Kirando'), ('kabwe', 'Kabwe'), ('karema', 'Karema'), ('manyovu', 'Manyovu'), ('kibirizi', 'Kibirizi'), ('kigoma', 'Kigoma'), ('mabamba', 'Mabamba'), ('mwanza', 'Mwanza'), ('sirari', 'Sirari'), ('kabanga', 'Kabanga'), ('musoma', 'Musoma'), ('rusumo', 'Rusumo'), ('mutukula', 'Mutukula'), ('bukoba', 'Bukoba'), ('murusagamba', 'Murusagamba'), ('murongo', 'Murongo'), ('bukoba_airport', 'Bukoba Airport'), ('jnia', 'JNIA'), ('kurasini', 'Kurasini'), ('tanga', 'Tanga'), ('horohoro', 'Horohoro'), ('bagamoyo', 'Bagamoyo'), ('kwala', 'Kwala'), ('holili', 'Holili'), ('tarakea', 'Tarakea'), ('kia', 'KIA'), ('tengeru', 'Tengeru'), ('namanga', 'Namanga')], max_length=50)),
                ('number_of_inspectors', models.PositiveIntegerField()),
                ('plant_consignments_certified', models.PositiveIntegerField()),
                ('phytosanitary_certificates_issued', models.PositiveIntegerField()),
                ('consignments_not_meeting_export_requirements', models.PositiveIntegerField()),
                ('export_non_compliance_measures', models.TextField()),
                ('plant_import_permits_issued', models.PositiveIntegerField()),
                ('imported_plant_consignments_verified', models.PositiveIntegerField()),
                ('imported_consignments_on_transit', models.PositiveIntegerField()),
                ('consignments_not_meeting_import_requirements', models.PositiveIntegerField()),
                ('import_non_compliance_measures', models.TextField()),
                ('import_challenges', models.TextField(blank=True)),
                ('pesticides_consignments_received_inspected', models.PositiveIntegerField()),
                ('pesticides_consignments_not_meeting_requirements', models.PositiveIntegerField()),
                ('pesticide_non_compliance_measures', models.TextField()),
                ('pesticide_challenges', models.TextField(blank=True)),
                ('field_visits', models.PositiveIntegerField()),
                ('surveillance_work', models.TextField()),
                ('key_pests_diseases_observed', models.TextField()),
                ('geographical_coverage_of_pests', models.TextField()),
                ('preliminary_measures_taken', models.TextField()),
                ('fields_crops_inspected', models.PositiveIntegerField()),
                ('crop_non_compliance_observed', models.TextField()),
                ('crop_non_compliance_measures', models.TextField()),
                ('pesticide_businesses_inspected', models.PositiveIntegerField()),
                ('pesticide_business_non_compliance', models.TextField(blank=True)),
                ('stakeholder_groups_met', models.PositiveIntegerField()),
                ('stakeholder_concerns', models.TextField()),
                ('other_field_work_activities', models.TextField()),
                ('community_meetings_attended', models.TextField()),
                ('community_concerns', models.TextField()),
                ('on_call_plant_health', models.TextField(blank=True)),
                ('on_call_pesticide_management', models.TextField(blank=True)),
                ('other_important_matters', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
