# Generated by Django 5.1 on 2024-08-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonalReports', '0002_zonalreport_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonalreport',
            name='zone',
            field=models.CharField(max_length=100),
        ),
    ]
