# Generated by Django 5.1 on 2024-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonalReports', '0003_alter_zonalreport_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonalreport',
            name='zone',
            field=models.CharField(choices=[('northernzone', 'Northern Zone'), ('easternzone', 'Eastern Zone'), ('westernzone', 'Western Zone'), ('southernzone', 'Southern Zone'), ('southernhighlands', 'SOUTHERN HIGHLANDS'), ('lakezone', 'LAKE ZONE'), ('centralzone', 'CENTRAL ZONE')], max_length=50),
        ),
    ]
