# Generated by Django 5.1 on 2024-08-19 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.now)),
                ('training_start_time', models.TimeField()),
                ('training_end_time', models.TimeField()),
                ('trainer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('training_type', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('field_demonstration', 'Field Demonstration')], max_length=50)),
                ('target_audience', models.CharField(choices=[('farmers', 'Farmers'), ('extension_officers', 'Extension Officers'), ('stakeholders', 'Stakeholders')], max_length=50)),
                ('training_topics', models.TextField()),
                ('training_methods', models.TextField()),
                ('skills_knowledge_gained', models.TextField()),
                ('assessments_conducted', models.TextField()),
                ('participant_feedback', models.TextField()),
                ('post_training_follow_up', models.TextField()),
                ('training_impact', models.TextField()),
                ('additional_notes', models.TextField(blank=True)),
                ('challenges_encountered', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
            ],
        ),
    ]
