# Generated by Django 5.1 on 2024-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='post_training_follow_up',
        ),
        migrations.AlterField(
            model_name='training',
            name='target_audience',
            field=models.CharField(choices=[('farmers', 'Farmers'), ('extension_officers', 'Extension Officers'), ('stakeholders', 'Stakeholders'), ('workers', 'Workers')], max_length=50),
        ),
    ]
